### ISSUE TITLE
Bug in v 0.2.0+

### ISSUE THREAD

**Issue by jelstongreen** [fal-ai/fal#137]
Since the latest release our fal task has started failing to run a python scripts and gives the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/fal", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 146, in cli
    run_fal(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 129, in run_fal
    _run(
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 185, in _run
    faldbt = FalDbt(
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 218, in __init__
    self.models, self.tests = _map_nodes_to_models(self._run_results, self._manifest)
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 519, in _map_nodes_to_models
    tests = manifest.get_tests()
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 128, in get_tests
    return list(
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 132, in <lambda>
    lambda node: DbtTest(node=node), self.nativeManifest.nodes.values()
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 54, in __post_init__
    self.name = node.test_metadata.name
AttributeError: 'ParsedSingularTestNode' object has no attribute 'test_metadata'
```

**Comment by mkam039** [comment]
Which version of dbt are you using?
