### ISSUE TITLE
KeyError: 'column_name'

### ISSUE THREAD

**Issue by jelstongreen** [fal-ai/fal#141]
Latest issue when using v0.2.2 -

```
Logged from file <class 'networkx.utils.decorators.argmap'> compilation 5, line 5
Traceback (most recent call last):
  File "/usr/local/bin/fal", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 154, in cli
    run_fal(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 136, in run_fal
    _run(
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 203, in _run
    faldbt = FalDbt(
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 221, in __init__
    self.models, self.tests = _map_nodes_to_models(self._run_results, self._manifest)
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 522, in _map_nodes_to_models
    tests = manifest.get_tests()
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 131, in get_tests
    return list(
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 135, in <lambda>
    lambda node: DbtTest(node=node), self.nativeManifest.nodes.values()
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 61, in __post_init__
    self.column = node.test_metadata.kwargs['column_name']
KeyError: 'column_name'
```

**Comment by mkam039** [comment]
Thanks for raising this issue. Does this mean that you have generic tests not attached to any columns? Which means that they are not associated with any models?

**Comment by jelstongreen** [comment]
Hi, we have model level tests and column level tests but not tests not assigned to anything afaik.

**Comment by mkam039** [comment]
Alright @jelstongreen, I just released another patch that should fix this error: https://pypi.org/project/fal/0.2.3/ 

Thank you very much for your time and patience 🙏 🙏 🙏

**Comment by jelstongreen** [comment]
Sorry @mkam039 but getting this now 
```
Logged from file <class 'networkx.utils.decorators.argmap'> compilation 5, line 5
Traceback (most recent call last):
  File "/usr/local/bin/fal", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 154, in cli
    run_fal(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 136, in run_fal
    _run(
  File "/usr/local/lib/python3.9/site-packages/fal/cli.py", line 203, in _run
    faldbt = FalDbt(
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 221, in __init__
    self.models, self.tests = _map_nodes_to_models(self._run_results, self._manifest)
  File "/usr/local/lib/python3.9/site-packages/faldbt/project.py", line 532, in _map_nodes_to_models
    if test.model == model.name:
AttributeError: 'DbtTest' object has no attribute 'model'
```

**Comment by mkam039** [comment]
@jelstongreen, you have an interesting test structure. Could we have a snippet of a schema.yml where a test is attached to a model but not to a specific column?

**Comment by jelstongreen** [comment]
@mkam039 here you go
```
  - name: model_x
    meta:
      owner: '@autho'
      team_owner: '@authorteam'
    description: A model
    columns:
      - name: model_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: valid_from
        description: The timestamp that the row is valid from
      - name: valid_to
        description: The timestamp that the row is valid to
      - name: is_currently_active_row
        description: >
          rows with is_currently_active_record is TRUE are currently active for each row
      - name: model_id
        tests:
          - reverse_relationships:
              to: ref('stg_model')
              field: model_id
              error_if: ">= 100"
              tags:
                - full-data-test
          - unique:
              where: "is_currently_active_record"
    tests:
      - dbt_utils.mutually_exclusive_ranges:
          lower_bound_column: valid_from
          upper_bound_column: valid_to
          partition_by: model_id
          gaps: not_allowed
```

**Comment by mkam039** [comment]
Alright, I think I found the issue. Should release another patch soon.

**Comment by mkam039** [comment]
@jelstongreen, could you try this patch: https://pypi.org/project/fal/0.2.4/

**Comment by jelstongreen** [comment]
@mkam039 Looks like that is working now, thank you!

**Comment by mkam039** [comment]
AWESOME! Thank you for your help!
