### ISSUE TITLE
pydantic 2 migration issues

### ISSUE THREAD

**Issue by chamini2** [fal-ai/fal#29]
Tested with the diff https://github.com/fal-ai/fal/compare/main...matteo/pydantic2-test

I was trying out what the migration to Pydantic 2 could look like and I get the following:

```py
from __future__ import annotations

from fal import cached, function


@cached
def my_cached_function():
    import datetime

    print("Cached function")
    return datetime.datetime.now()


@function(
    machine_type="S",
    serve=True,
)
def hello_query(name: str):
    started_at = my_cached_function()
    print(started_at, f"Messaged by: {name}")
    return f"Hello, {name}"

# Now with pydantic dataclasses for the payload
from pydantic.dataclasses import dataclass

@dataclass
class HelloModel:
    name: str

@function(
    machine_type="S",
    serve=True,
)
def hello_dataclass(data: HelloModel):
    started_at = my_cached_function()
    print(started_at, f"Messaged by: {data.name}")
    return f"Hello, {data.name}"
```

Runing the query version it works as expected and can be used

```
❯ fal fn run t/other.py hello_query

...

2024-01-12 18:23:30.971 [info     ] Installing collected packages: typing-extensions, tblib, sniffio, protobuf, platformdirs, idna, h11, grpcio, dill, click, annotated-types, uvicorn, pydantic-core, isolate, anyio, starlette, pydantic, fastapi
2024-01-12 18:23:33.576 [info     ] Successfully installed annotated-types-0.6.0 anyio-4.2.0 click-8.1.7 dill-0.3.7 fastapi-0.109.0 grpcio-1.60.0 h11-0.14.0 idna-3.6 isolate-0.12.3 platformdirs-4.1.0 protobuf-4.25.2 pydantic-2.5.3 pydantic-core-2.14.6 sniffio-1.3.0 starlette-0.35.1 tblib-3.0.0 typing-extensions-4.9.0 uvicorn-0.25.0
2024-01-12 18:23:33.850 [info     ]
2024-01-12 18:23:33.850 [info     ] [notice] A new release of pip is available: 23.3.1 -> 23.3.2
2024-01-12 18:23:33.850 [info     ] [notice] To update, run: python -m pip install --upgrade pip
2024-01-12 18:23:35.990 [stdout   ] Compression complete. Uploading it...
2024-01-12 18:23:36.127 [stdout   ] Upload complete.
2024-01-12 18:23:36.128 [stdout   ]
2024-01-12 18:23:57.195 [info     ] Access your exposed service at https://1774a50b-9241-4db0-ab5b-0457cc6a5b9f.gateway.alpha.fal.ai
2024-01-12 18:23:59.430 [stderr   ] INFO:     Started server process [42]
2024-01-12 18:23:59.431 [stderr   ] INFO:     Waiting for application startup.
2024-01-12 18:23:59.432 [stderr   ] INFO:     Application startup complete.
2024-01-12 18:23:59.432 [stderr   ] INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2024-01-12 18:28:33.325 [stdout   ] INFO:     10.52.4.70:42250 - "GET / HTTP/1.1" 405 Method Not Allowed
2024-01-12 18:28:52.066 [stdout   ] INFO:     10.52.4.70:48494 - "POST / HTTP/1.1" 422 Unprocessable Entity
2024-01-12 18:28:57.409 [stdout   ] Cached function
2024-01-12 18:28:59.038 [stdout   ] 2024-01-12 18:28:57.409594 Messaged by: matteo
2024-01-12 18:28:59.039 [stdout   ] INFO:     10.52.4.70:56564 - "POST /?name=matteo HTTP/1.1" 200 OK
```

But when I try to use the dataclass version I get an error

```
❯ fal fn run t/other.py hello_dataclass
2024-01-12 18:30:44.615 [info     ] Access your exposed service at https://4c793170-2fe2-4fbe-a633-64d52d1e704f.gateway.alpha.fal.ai
Error while deserializing the given object
```

Notice this error while deserializing seems to be local (gRPC deserializing?)

Specifically, running the above command with `--debug` I get

```
...
│ .../python3.11/site-packages/isolate/connections │
│ /grpc/interface.py:29 in _                                                                       │
│                                                                                                  │
│   26                                                                                             │
│   27 @from_grpc.register                                                                         │
│   28 def _(message: definitions.SerializedObject) -> Any:                                        │
│ ❱ 29 │   return load_serialized_object(                                                          │
│   30 │   │   message.method,                                                                     │
│   31 │   │   message.definition,                                                                 │
│   32 │   │   was_it_raised=message.was_it_raised,                                                │
│                                                                                                  │
│ .../python3.11/site-packages/isolate/connections │
│ /common.py:76 in load_serialized_object                                                          │
│                                                                                                  │
│    73 │   │   │   importlib.import_module(serialization_method)                                  │
│    74 │   │   )                                                                                  │
│    75 │                                                                                          │
│ ❱  76 │   with _step("deserializing the given object"):                                          │
│    77 │   │   result = serialization_backend.loads(raw_object)                                   │
│    78 │                                                                                          │
│    79 │   if was_it_raised:                                                                      │
│                                                                                                  │
│ .../python3.11/contextlib.py:155 in __exit__                │
│                                                                                                  │
│   152 │   │   │   │   # tell if we get the same exception back                                   │
│   153 │   │   │   │   value = typ()                                                              │
│   154 │   │   │   try:                                                                           │
│ ❱ 155 │   │   │   │   self.gen.throw(typ, value, traceback)                                      │
│   156 │   │   │   except StopIteration as exc:                                                   │
│   157 │   │   │   │   # Suppress StopIteration *unless* it's the same exception that             │
│   158 │   │   │   │   # was passed to throw().  This prevents a StopIteration                    │
│                                                                                                  │
│ .../python3.11/site-packages/isolate/connections │
│ /common.py:42 in _step                                                                           │
│                                                                                                  │
│    39 │   try:                                                                                   │
│    40 │   │   yield                                                                              │
│    41 │   except BaseException as exception:                                                     │
│ ❱  42 │   │   raise SerializationError("Error while " + message) from exception                  │
│    43                                                                                            │
│    44                                                                                            │
│    45 def as_serialization_method(backend: Any) -> SerializationBackend:                         │
...
```

**Comment by lmmx** [comment]
I get the impression from your description/branch name you saw this as a v2 regression @chamini2 but this reproduces on `main` actually.

The `hello_dataclass` function does not actually serialise successfully in Pydantic 1.x from what I can see: but the `serve=True` parameter hides this by successfully starting a Uvicorn server.

There might indeed be problems with Pydantic 2, but I'd think it'd be best to start from a working v1.x baseline here.

<details><summary>Click to show edited version of the repro script</summary>

```py
from __future__ import annotations

from fal import cached, function


@cached
def my_cached_function():
    import datetime

    print("Cached function")
    return datetime.datetime.now()


@function(machine_type="S", serve=False)
def hello_query():
    name: str = "Louis"
    started_at = my_cached_function()
    print(started_at, f"Messaged by: {name}")
    return f"Hello, {name}"


# Now with pydantic dataclasses for the payload
from pydantic.dataclasses import dataclass


@dataclass
class HelloModel:
    name: str


@function(machine_type="S", serve=False)
def hello_dataclass():
    data: HelloModel = HelloModel(name="Louis")
    started_at = my_cached_function()
    print(started_at, f"Messaged by: {data.name}")
    return f"Hello, {data.name}"
```

</details>

- I changed the decorator param to `serve=False` to reproduce a little more minimally.
- I removed the string/dataclass from the function signatures just to simplify calling it.

We can run `hello_query` 

```sh
$ fal fn run demo.py hello_query
2024-01-18 22:11:38.933 [stdout   ] Cached function
2024-01-18 22:11:38.933 [stdout   ] 2024-01-18 22:11:38.932910 Messaged by: Louis
```

We cannot run `hello_dataclass`

```sh
$ fal fn run demo.py hello_dataclass
Error while serializing the given object
```

I would try a debugging approach that stays in Python rather than CLI (shell level) to get more visibility.

The stack trace shows it's emerging from dill

What's more if I use a Pydantic model it fails more verbosely [error shown with no `--debug` flag] and seems to indicate that the virtualenv cached directory does not have the necessary Pydantic module...

```
$ fal fn run demo.py hello_data_model
2024-01-18 22:38:55.311 [error    ] Traceback (most recent call last):
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/isolate/connections/common.py", line 40, in _step
    yield
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/isolate/connections/common.py", line 77, in load_serialized_object
    result = serialization_backend.loads(raw_object)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/dill/_dill.py", line 301, in loads
    return load(file, ignore, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/dill/_dill.py", line 432, in find_class
    return StockUnpickler.find_class(self, module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pydantic'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/isolate/connections/grpc/agent.py", line 113, in execute_function
    function = from_grpc(function)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/isolate/connections/grpc/interface.py", line 29, in _
    return load_serialized_object(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/isolate/connections/common.py", line 76, in load_serialized_object
    with _step("deserializing the given object"):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.cache/isolate/virtualenv/dd85ba8a65db645667152bcadfce1749d4fbd40765c63ba1d368c48eafe9c34e/lib/python3.11/site-packages/isolate/connections/common.py", line 42, in _step
    raise SerializationError("Error while " + message) from exception
isolate.connections.common.SerializationError: Error while deserializing the given object

Function execution quit unexpectedly. Error contents: The function function could not be deserialized.
```

I get the impression this is the same error as the one raised from the Pydantic dataclass, but a bit clearer (no need to `--debug` to see it)

I checked and in fact this seems to have been cut off from the traceback you shared, it's the upstream cause of the 2nd exception in both cases though.

**Comment by lmmx** [comment]
Discussed this with @isidentical who suggests the following repro:

Pydantic 2:

```py
# demo_2.py
import fal
from fal.toolkit import File
from pydantic import BaseModel, Field


class Input(BaseModel):
    prompt: str
    num_steps: int = Field(default=2, ge=1, le=10)


class Output(BaseModel):
    file: File


@fal.function(_scheduler="nomad", requirements=["pydantic<2"])
def generate(input: Input) -> Output:
    file = File.from_bytes(input.prompt.encode() * input.num_steps, "text/plain")
    return Output(file=file)


if __name__ == "__main__":
    # Run the function locally
    output = generate(Input(prompt="Hello, world!"))
    print(f"{output!r}")
```

That works OK (may time out, just repeat the command to run again)

Then, make 2 modifications to the `fal` project source:

- 6b851ac bump Pydantic pin to 2.5.3
- dfeae0f comment out pre-v2 Pydantic patch calls

Which allow us to modify the `requirements` line in the `@fal.function(...)` decorator in our repro script:

```py
# demo_3.py
import fal
from fal.toolkit import File
from pydantic import BaseModel, Field


class Input(BaseModel):
    prompt: str
    num_steps: int = Field(default=2, ge=1, le=10)


class Output(BaseModel):
    file: File


@fal.function(_scheduler="nomad", requirements=["pydantic>=2"])
def generate(input: Input) -> Output:
    file = File.from_bytes(input.prompt.encode() * input.num_steps, "text/plain")
    return Output(file=file)


if __name__ == "__main__":
    # Run the function locally
    output = generate(Input(prompt="Hello, world!"))
    print(f"{output!r}")
```

This no longer succeeds.
