### ISSUE TITLE
import fal_client:  TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by githubloader** [fal-ai/fal#350]
Just curious if anyone else getting this error message after "import fal_client" in Python?
Tried just using pip and still the same error message.

import asyncio
import fal_client

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/3Vf-bV_HfJWj/lib/python3.8/site-packages/fal_client/__init__.py", line 1, in <module>
    from fal_client.client import (
  File "/home/user/.local/share/virtualenvs/3Vf-bV_HfJWj/lib/python3.8/site-packages/fal_client/client.py", line 23, in <module>
    AnyJSON = dict[str, Any]
TypeError: 'type' object is not subscriptable

My system:
Ubuntu 20.04.6 LTS
Python 3.8.10
pipenv, version 11.9.0

**Comment by chamini2** [comment]
thanks for the report, will fix it
