### ISSUE TITLE
Write_to_model target error: multiple values for argument 'target_1'

### ISSUE THREAD

**Issue by quinnhornblow** [fal-ai/fal#438]
First time using fal so I am starting small. I have a simple python file that reads:

```
import pandas as pd
df: pd.DataFrame = ref("sites")
print(df.head())
write_to_model(df, "selected_sites", mode="overwrite")
```

I then run `fal flow run --experimental-models`
I should note that this is a stand alone model, there is no meta: --before/--after references.

Upon running the ref is loaded and prints to the terminal. But then throws  `TypeError: multiple values for argument 'target_1'`

Any thoughts? I've replicated on Ubuntu. Full error log below.

OS: Windows
fal --version 0.3.4
dbt --version 1.1.1
Adapter being used: postgres

Error in script (model: models\master_tables\selected_sites.py):
Traceback (most recent call last):
  File "env\lib\site-packages\fal\run_scripts.py", line 24, in _prepare_exec_script
    script.exec(faldbt)
  File "env\lib\site-packages\fal\fal_script.py", line 130, in exec
    exec(program, exec_globals)
  File "models\master_tables\selected_sites.py", line 7, in <module>
    write_to_model(df, "selected_sites", mode="overwrite")
  File "env\lib\site-packages\fal\telemetry\telemetry.py", line 324, in wrapper
    sig = inspect.signature(func).bind(*func_args, **func_kwargs)
  File "C:\Python310\lib\inspect.py", line 3179, in bind
    return self._bind(args, kwargs)
  File "C:\Python310\lib\inspect.py", line 3118, in _bind
    raise TypeError(
TypeError: multiple values for argument 'target_1'

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "env\Scripts\fal.exe\__main__.py", line 7, in <module>
  File "env\lib\site-packages\fal\cli\cli.py", line 18, in cli
    _cli(argv)
  File "env\lib\site-packages\fal\telemetry\telemetry.py", line 338, in wrapper
    result = func(*func_args, **func_kwargs)
  File "env\lib\site-packages\fal\cli\cli.py", line 44, in _cli
    fal_flow_run(parsed)
  File "env\lib\site-packages\fal\cli\flow_runner.py", line 74, in fal_flow_run
    run_serial(fal_dbt=fal_dbt, parsed=parsed, node_graph=node_graph)
  File "env\lib\site-packages\fal\cli\flow_runner.py", line 46, in run_serial
    _run_sub_graph(index, parsed, node_graph, execution_plan, fal_dbt)
  File "env\lib\site-packages\fal\cli\flow_runner.py", line 156, in _run_sub_graph
    raise_for_run_results_failures(**fal_nodes_results)
  File "env\lib\site-packages\fal\run_scripts.py", line 41, in raise_for_run_results_failures
    raise RuntimeError(f"Error in scripts {str.join(', ', failure_ids)}")
RuntimeError: Error in scripts (model: models\master_tables\selected_sites.py)

**Comment by quinnhornblow** [comment]
Found my mistake, should have been `write_to_model(df, mode="overwrite")`

**Comment by mederka** [comment]
Thank you for trying fal, @quinnhornblow 🙏. Let us know if you run into any other issues.
