### ISSUE TITLE
Getting error ModuleNotFoundError: No module named 'dbt.contracts.graph.parsed'

### ISSUE THREAD

**Issue by SBurwash** [fal-ai/fal#734]
**Describe the bug**
Since yesterday, getting this bug: `ModuleNotFoundError: No module named 'dbt.contracts.graph.parsed'`

**Your environment**
- OS: 
- Paste the following commands output:
```
fal --version
dbt --version
```
0.72 locally, but I believe it's higher in production
1.3.2
- Adapter being used:  

**How to reproduce**

Simply run fal:run
**Expected behavior**
Not crashing

**Actual behavior**
Crashing

**Screenshots**

**Additional context**

**Comment by SBurwash** [comment]
Full error: ```Traceback (most recent call last):
  File "/project/.meltano/utilities/dbt-fal/venv/bin/fal", line 5, in <module>
    from fal.cli import cli
  File "/project/.meltano/utilities/dbt-fal/venv/lib/python3.8/site-packages/fal/__init__.py", line 3, in <module>
    from faldbt.project import (
  File "/project/.meltano/utilities/dbt-fal/venv/lib/python3.8/site-packages/faldbt/project.py", line 18, in <module>
    from dbt.contracts.graph.parsed import (
ModuleNotFoundError: No module named 'dbt.contracts.graph.parsed'```

**Comment by chamini2** [comment]
Thanks for reaching out about this @SBurwash !

I think I had only seen this issue for `1.4` dbt versions. Maybe the production dbt version is not pinned to `1.3`?

I am currently working on fixing this and will update here as soon as we have 1.4 suppport.

**Comment by SBurwash** [comment]
Hey @chamini2, thanks for the quick response!

Here is my output for dbt-bigquery --version:

```
2023-01-31T19:00:31.206126Z [info     ] Environment 'prod' is active
Core:
  - installed: 1.3.2
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.3.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
  ```

It seems I'm still on 1.3 though...

**Comment by SBurwash** [comment]
Would this be linked to a recent rollout? Would there be a way to quickly revert to a previous version?

**Comment by SBurwash** [comment]
As a quick fix I **reverted back to version 0.7.2**
